### ISSUE TITLE
Cannot save volumes using the button in the volume widget

### ISSUE THREAD

**Issue by dittothat** [ibme-qubic/quantiphyse#31]
In quantiphyse v.0.9.3.post2 installed via pypi, when I try to save a volume using the save button at the bottom of the volumes widget I get an error:
![image](https://user-images.githubusercontent.com/31418568/64989583-d36a4b80-d89b-11e9-8006-d6a6d63a519e.png)
I select the file location and name in standard ubuntu save dialog, and when I click save the error above appears.
I can still save the file, however, if I select the volume and then do file>save current data or ctrl+s.

**Comment by mcraig-ibme** [comment]
Fixed on master. Odd one - although the bug is clear in the code I couldn't actually get it to reproduce myself. Awaiting pypi release.

**Comment by mcraig-ibme** [comment]
v0.9.5
