### ISSUE TITLE
Error u'out.nii.gz' - any idea how to fix?

### ISSUE THREAD

**Issue by Pavel2020Quant** [ibme-qubic/quantiphyse#34]
I'm unable to register images at the end of the Quantiphyse Pipeline and the application crashes (see screenshot). I have version 0.8 Quantiphyse and FSL 6.0.3:b862cdd5 (downloaded June 2020). 

It only happens when I use the structural image. If I skip the structural image, everything works fine.

Any idea how to fix the this error?

thanks,

Pavel

<img width="1386" alt="Error Message" src="https://user-images.githubusercontent.com/66541609/83958923-1c549c80-a83d-11ea-968b-d77df63f2efa.png">

**Comment by mcraig-ibme** [comment]
Apologies for slow response. If this is still causing a problem could you tell me what the environment variable FSLOUTPUTTYPE is set to?

**Comment by Pavel2020Quant** [comment]
Hi Martin,

I had a personal family problem and had to put the project on hold. I will reach out to you with any issues.

Thank you,

Pavel

**Comment by mcraig-ibme** [comment]
Closing as not clear how to reproduce can reopen if more information available
