### ISSUE TITLE
Missing qboldR2p when using Quantitative BOLD

### ISSUE THREAD

**Issue by linhnnle** [ibme-qubic/quantiphyse#40]
Hi all, 

I'm having trouble when running qBOLD on Quantiphyse. I got this error message when clicking Run the Quantitative BOLD. I am using Linux (Centos 7). 

Unknown model: qboldR2p

Details:

Traceback (most recent call last):

File "/usr/local/lib/python3.6/site-packages/quantiphyse/gui/widgets.py", line 1334, in _finished
raise exception

File "/usr/local/lib/python3.6/site-packages/quantiphyse/processes/process.py", line 201, in execute
self.run(options)

File "/home/linh/.local/lib/python3.6/site-packages/quantiphyse_fabber/process.py", line 155, in run
known_options = api.get_options(generic=True, model=options.get("model", None), method=options.get("method", None))[0]

File "/home/linh/.local/lib/python3.6/site-packages/fabber/api_cl.py", line 196, in get_options
stdout = self._call(help=True, model=model)

File "/home/linh/.local/lib/python3.6/site-packages/fabber/api_cl.py", line 325, in _call
exe = self._get_exe(options)

File "/home/linh/.local/lib/python3.6/site-packages/fabber/api_cl.py", line 374, in _get_exe
raise ValueError("Unknown model: %s" % model)

ValueError: Unknown model: qboldR2p

**Comment by mcraig-ibme** [comment]
Hi, sorry for the delay in replying.

To run the quantitative BOLD widget you will need a copy of Fabber with the qBOLD model enabled. The easiest way to get this is to install FSL 6.0.5 (previous versions of FSL did not include this model). It is also possible to build and install the model using an earlier version of FSL, but this is probably more difficult. If you want to go down this route, let me know and I will provide the instructions.

**Comment by linhnnle** [comment]
It works! Thank you so much!

**Comment by linhnnle** [comment]
I have another question for the Mac version of Quantiphyse. I finished installing and everything looks fine, but when I type **quantiphyse** in the Terminal to open it. It showed the icon but there is no GUI shown in the screen. Is it because of my Mac's memory/RAM?

**Comment by mcraig-ibme** [comment]
Please check https://quantiphyse.readthedocs.io/en/latest/basics/install.html as there are several 'Notes' that address Mac-specific problems. If still not working, please open a new issue with description of Mac version, how Quantiphyse was installed and any messages reported to console. RAM should not generally be an issue at startup.
