### ISSUE TITLE
kMeans clustering error

### ISSUE THREAD

**Issue by smcch** [ibme-qubic/quantiphyse#41]
Hi, I'm trying to run kmeans clustering but I got an error : 'unexpected keyword argument n_jobs'.  I'm working with a 4D image.

Thanks for your help

OS: Windows 10
Python: 3.9

![error](https://user-images.githubusercontent.com/87584415/140635799-4ac5912c-e0b0-40a0-8671-64a654325e84.png)

**Comment by mcraig-ibme** [comment]
Fixed by d9fe93f05383e7d08ac21cbd7102778e10da0b32
