### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by opennog** [ibme-qubic/quantiphyse#45]
Hi - 
I had a working version of quantiphyse that out of the blue stopped working. So I removed the conda environment and proceed to start it all over again. Installation is successful however I still get the same error when trying to run it.

$ quantiphyse
Traceback (most recent call last):
  File "/home/oscar/anaconda3/envs/qp2/bin/quantiphyse", line 5, in <module>
    from quantiphyse.qpmain import main
  File "/home/oscar/anaconda3/envs/qp2/lib/python3.8/site-packages/quantiphyse/qpmain.py", line 30, in <module>
    from PySide2 import QtGui, QtCore, QtWidgets
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/oscar/anaconda3/envs/qp2/lib/python3.8/site-packages/PySide2/QtGui.abi3.so)

I haven't been able to find the solution.
Thank you.

**Comment by opennog** [comment]
It was struggling me a bit but found the solution. 
LD_LIBRARY_PATH="/opt/afni-latest/:/usr/lib/x86_64-linux-gnu/*"

The * needs to be in the LD_LIBRARY_PATH

**Comment by mcraig-ibme** [comment]
This is an issue with the installation of Qt rather than quantiphyse - normally qt would be installed in the conda environment with quantiphyse  but the error suggests that it is looking at a system library which isn't compatible with the version of pyside. Glad you found a solution.
