### ISSUE TITLE
Used fslpython to install but can't run quantiphyse

### ISSUE THREAD

**Issue by Chenjennie** [ibme-qubic/quantiphyse#46]
Hi there, I was able to add the path containing the quantiphyse executable to my bash_profile, but when I typed quantiphyse I got the following error:

Traceback (most recent call last):
  File "/home/[redacted]/.local/bin/quantiphyse", line 6, in <module>
    from quantiphyse.qpmain import main
  File "/home/[redacted]/.local/lib/python3.7/site-packages/quantiphyse/qpmain.py", line 30, in <module>
    from PySide2 import QtGui, QtCore, QtWidgets
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /software/matlab/R2020b/bin/glnxa64/libQt5Core.so.5)

Am I missing some program that has this /lib64/libstdc++.so.6 file?

Thanks!

**Comment by Chenjennie** [comment]
I've continued to work on troubleshooting. It looks like the CXXABI importerror was because that version of CXXABI was missing in the lib64/libstdc++.so.6 file. I checked my LD_LIBRARY_PATH variable and /lib64 was listed first. When I loaded gcc/6.4.0 in my terminal, that moved /hpc/software/gcc/6.4.0/lib64 to the top of my LD_LIBRARY_PATH and now I get a different error when trying to run quantiphyse:

Traceback (most recent call last):
  File "/home/[redacted]/.local/bin/quantiphyse", line 6, in <module>
    from quantiphyse.qpmain import main
  File "/home/[redacted]/.local/lib/python3.7/site-packages/quantiphyse/qpmain.py", line 30, in <module>
    from PySide2 import QtGui, QtCore, QtWidgets
ImportError: /home/[redacted]/.local/lib/python3.7/site-packages/PySide2/Qt/lib/libQt5Qml.so.5: symbol _ZTI26QAbstractDynamicMetaObject, version Qt_5_PRIVATE_API not defined in file libQt5Core.so.5 with link time reference

Do I just not have the right environment loaded?
Thanks again.

**Comment by mcraig-ibme** [comment]
I would suggest installing quantiphyse in its own conda environment, using fslpython is not recommended any more. It looks like PySide/Qt5 is not compatible with the libraries in fslpython and if you try to change things to fix this you could end up breaking FSL.

**Comment by mcraig-ibme** [comment]
Closing as can't generally guarantee that installation using fslpython will work.
