### ISSUE TITLE
Installation errors on Python 3.6

### ISSUE THREAD

**Issue by tomfrankkirk** [ibme-qubic/quantiphyse#48]
Feedback suggests installation is not reliable on Python 3.6. I think this may be down to Cython interacting badly with old Numpy (in particular "deprecated alias in NumPy") and Pillow (see attached error log). Installation on RTD does suggest 3.7 upwards, maybe this suggestion can be made a bit firmer?

[pillow-error.txt](https://github.com/physimals/quantiphyse/files/10838879/pillow-error.txt)

**Comment by mcraig-ibme** [comment]
The pillow error relates to building some native code - the jpeg headers are not found which on linux usually means the corresponding development package (e.g. libjpeg-dev) is not installed. Unfortunately many linux distros do not install development packages by default.

Not sure why this would be a problem on python 3.6 particularly, perhaps for more recent python versions there are precompiled binary packages available for pillow.

It isn't really a python version incompatibility but 3.6 is quite old now. I'm happy to strongly recommend 3.7+ and have updated the docs to this effect.
